chat_id = "your_chat_id"
bot_token = "your_bot_token"

# Get notified about tables posted in Lombardia and Veneto in the "Arredamento e Casalinghi" category
[[item]]
keyword = "table"
region = [4, 6]
category = 14

# Get notified about chairs posted in Rome, with the word chair in the title
[[item]]
keyword = "chair"
region = 11
province = 4
city = 058091
search_only_title = true