version: "3.3"
services:
  subitobot:
    platform: linux/amd64
    image: ghcr.io/sasso0101/subitobot:latest
    container_name: subitobot
    restart: "no"
    volumes:
       - ./data:/subitobot/data